In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [0]:
from google.colab import drive

In [5]:
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
df_prot_fin = pd.read_csv('/content/drive/My Drive/Colab Notebooks/twenty_five.csv')

In [7]:
df_prot_fin.classification.value_counts()

HYDROLASE                        45353
TRANSFERASE                      35700
OXIDOREDUCTASE                   33785
IMMUNE SYSTEM                    13921
LYASE                            11617
HYDROLASE/HYDROLASE INHIBITOR    10131
VIRAL PROTEIN                     8304
TRANSPORT PROTEIN                 8249
TRANSCRIPTION                     8013
VIRUS                             6935
ISOMERASE                         6326
SIGNALING PROTEIN                 6081
LIGASE                            4874
MEMBRANE PROTEIN                  4672
PROTEIN BINDING                   4534
Name: classification, dtype: int64

### Creating a new feature columns which contains our N-grams 

In [0]:
from nltk import word_tokenize, ngrams

In [0]:
def n_grams(cols):
    #cols[0] = sequence
    return [(''.join(x)) for x in ngrams(cols, 4)]

df_prot_fin["N_seq"] = df_prot_fin['sequence'].apply(n_grams)
#df_prot_fin["N_seq"] =df_prot_fin["N_seq"].astype(str)

In [0]:
df_prot_fin.head(2)

Unnamed: 0 structureId classification  \
0          67        117E      HYDROLASE   
1          68        117E      HYDROLASE   

                                            sequence chainId  seq_length  \
0  TYTTRQIGAKNTLEYKVYIEKDGKPVSAFHDIPLYADKENNIFNMV...       A         286   
1  TYTTRQIGAKNTLEYKVYIEKDGKPVSAFHDIPLYADKENNIFNMV...       B         286   

                                               N_seq  
0  [TYTT, YTTR, TTRQ, TRQI, RQIG, QIGA, IGAK, GAK...  
1  [TYTT, YTTR, TTRQ, TRQI, RQIG, QIGA, IGAK, GAK...

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer

X_train, X_test,y_train,y_test = train_test_split(df_prot_fin['sequence'], df_prot_fin['classification'], test_size = 0.3, 
                                                  random_state = 101)bold text

vectorizer = CountVectorizer(analyzer = "char_wb", ngram_range = (4,4), min_df= 10, 
                             lowercase=True, max_df=0.9, max_features=5000)
X_train_onehot = vectorizer.fit_transform(X_train)

In [0]:
sample = df_prot_fin.sample(n=100000, replace=True)

In [69]:
sample.classification.value_counts()

HYDROLASE                        21525
TRANSFERASE                      17037
OXIDOREDUCTASE                   16005
IMMUNE SYSTEM                     6711
LYASE                             5654
HYDROLASE/HYDROLASE INHIBITOR     4931
TRANSPORT PROTEIN                 4045
TRANSCRIPTION                     3973
VIRAL PROTEIN                     3953
VIRUS                             3312
SIGNALING PROTEIN                 3043
ISOMERASE                         3016
LIGASE                            2376
MEMBRANE PROTEIN                  2276
PROTEIN BINDING                   2143
Name: classification, dtype: int64

In [0]:
from nltk import word_tokenize, ngrams

In [0]:
def n_grams(cols):
    #cols[0] = sequence
    return [(''.join(x)) for x in ngrams(cols, 4)]

sample["N_seq"] = sample['sequence'].apply(n_grams)
#sample["N_seq"] =sample["N_seq"].astype(str)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
train_X, test_X, y_train, y_test = train_test_split(
sample["N_seq"], sample["classification"], test_size=0.33, random_state=1000)

In [13]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=15000)
tokenizer.fit_on_texts(train_X)

Using TensorFlow backend.


In [0]:
X_train = tokenizer.texts_to_sequences(train_X)
X_test = tokenizer.texts_to_sequences(test_X)

vocab_size = len(tokenizer.word_index) + 1  

#print(sentences_train[2])
#print(X_train[2])

In [78]:
max_len = max([len(i) for i in X_train])
print(max_len)

3827


In [21]:
print(X_train[0])

[1088, 5651, 1060, 505, 1428, 340, 1997, 5348, 3899, 2402, 12365, 1265, 1750, 8861, 10943, 13291, 45, 6757, 4409, 9853, 6123, 12619, 1602, 14449, 11864, 2124, 11947, 4691, 9239, 10341, 4014, 10267, 6982, 3160, 12689, 14162, 716, 1611, 1366, 1071, 1189, 371, 60, 545, 1050, 3298, 6124, 7684, 11780, 14832, 149, 12620, 13106, 1901, 9240, 9659, 9660, 3237, 8186, 12035, 7246, 2451, 9916, 1473, 3637, 7555, 6478, 14726, 1640, 207, 12690, 9557, 13202, 13959, 8591, 7591, 8392, 5979, 4692, 4550, 6935, 2268, 554, 1180, 212, 1294, 6125, 13021, 14923, 601, 1429, 3699, 3615, 1784, 8696, 5536, 1568, 9375, 14638, 9800, 1499, 11583, 3422, 201, 870, 79, 81, 6887, 14163, 9181, 1152, 12200, 8337, 10593, 13203, 845, 667, 48, 1618, 9313, 2388, 6266, 3392, 7462, 825, 10192]


In [0]:
from keras.preprocessing.sequence import pad_sequences

maxlen = 2000

X_train = pad_sequences(X_train, padding='post', maxlen=maxlen)
X_test = pad_sequences(X_test, padding='post', maxlen=maxlen)

In [23]:
print(X_train[0])

[1088 5651 1060 ...    0    0    0]


In [24]:
from keras.models import Sequential
from keras import layers

embedding_dim = 200

model = Sequential()
model.add(layers.Embedding(input_dim=vocab_size, 
                           output_dim=embedding_dim, 
                           input_length=maxlen))
model.add(layers.Flatten())
model.add(layers.Dense(50, activation='relu'))
model.add(layers.Dense(15, activation='softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 2000, 200)         31751600  
_________________________________________________________________
flatten_1 (Flatten)          (None, 400000)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 50)                20000050  
_________________________________________________________________
dense_2 (Dense)              (None, 15)                765       
Total params: 51,752,415
Trainable params: 51,752,415
Non-trainable params: 0
_________________________________________________________________


In [0]:
y_train1 = pd.get_dummies(y_train).values


In [0]:
y_test1 = pd.get_dummies(y_test).values

In [27]:
history = model.fit(X_train, y_train1,
                    epochs=5,
                    verbose=1,
                    validation_data=(X_test, y_test1),
                    batch_size=20)

Instructions for updating:
Use tf.cast instead.
Train on 67000 samples, validate on 33000 samples
Epoch 1/5
67000/67000 [==============================] - 263s 4ms/step - loss: 1.0472 - acc: 0.7005 - val_loss: 0.5775 - val_acc: 0.8460
Epoch 2/5
67000/67000 [==============================] - 259s 4ms/step - loss: 0.2921 - acc: 0.9324 - val_loss: 0.5857 - val_acc: 0.8614
Epoch 3/5
67000/67000 [==============================] - 259s 4ms/step - loss: 0.2230 - acc: 0.9484 - val_loss: 0.5980 - val_acc: 0.8571
Epoch 4/5
67000/67000 [==============================] - 259s 4ms/step - loss: 0.2019 - acc: 0.9517 - val_loss: 0.8237 - val_acc: 0.8504
Epoch 5/5
67000/67000 [==============================] - 259s 4ms/step - loss: 0.1828 - acc: 0.9529 - val_loss: 0.8257 - val_acc: 0.8449


In [0]:
from sklearn.metrics import accuracy_score

In [90]:
loss, accuracy = model.evaluate(X_train, y_train1, verbose=False)
accuracy

0.9592388059701492

In [0]:
loss, accuracy = model.evaluate(X_test, y_test1, verbose=False)


In [92]:
accuracy

0.8636060606060606

15

In [0]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents

Using TensorFlow backend.


In [0]:
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [0]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[46, 26], [45, 1], [27, 43], [28, 1], [12], [37], [43, 43], [12, 45], [43, 1], [13, 15, 26, 34]]


In [0]:
import tensorflow as tf

In [0]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
#padded_docs1 = tf.cast(padded_docs, tf.float32)

[[46 26  0  0]
 [45  1  0  0]
 [27 43  0  0]
 [28  1  0  0]
 [12  0  0  0]
 [37  0  0  0]
 [43 43  0  0]
 [12 45  0  0]
 [43  1  0  0]
 [13 15 26 34]]


In [0]:
print(padded_docs1)


Tensor("Cast_1:0", shape=(10, 4), dtype=float32)


In [0]:
session = tf.Session()
session.run(padded_docs1)

array([[46., 26.,  0.,  0.],
       [45.,  1.,  0.,  0.],
       [27., 43.,  0.,  0.],
       [28.,  1.,  0.,  0.],
       [12.,  0.,  0.,  0.],
       [37.,  0.,  0.,  0.],
       [43., 43.,  0.,  0.],
       [12., 45.,  0.,  0.],
       [43.,  1.,  0.,  0.],
       [13., 15., 26., 34.]], dtype=float32)

In [0]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [0]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_4 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 69.999999


In [0]:
from keras.preprocessing.text import Tokenizer


In [0]:
max_words = 10000

text = 'Decreased glucose-6-phosphate dehydrogenase activity along with oxidative stress affects visual contrast sensitivity in alcoholics.'


In [0]:
t = Tokenizer()

t.fit_on_texts(text)

sequences = t.texts_to_sequences(text)

print("sequences : ",sequences,'\n')

print("word_index : ",t.word_index)

sequences :  [[8], [2], [7], [12], [2], [5], [1], [2], [8], [], [14], [9], [16], [7], [6], [1], [2], [], [19], [], [17], [10], [6], [1], [17], [10], [5], [3], [2], [], [8], [2], [10], [15], [8], [12], [6], [14], [2], [11], [5], [1], [2], [], [5], [7], [3], [4], [13], [4], [3], [15], [], [5], [9], [6], [11], [14], [], [20], [4], [3], [10], [], [6], [21], [4], [8], [5], [3], [4], [13], [2], [], [1], [3], [12], [2], [1], [1], [], [5], [18], [18], [2], [7], [3], [1], [], [13], [4], [1], [16], [5], [9], [], [7], [6], [11], [3], [12], [5], [1], [3], [], [1], [2], [11], [1], [4], [3], [4], [13], [4], [3], [15], [], [4], [11], [], [5], [9], [7], [6], [10], [6], [9], [4], [7], [1], []] 

word_index :  {'s': 1, 'e': 2, 't': 3, 'i': 4, 'a': 5, 'o': 6, 'c': 7, 'd': 8, 'l': 9, 'h': 10, 'n': 11, 'r': 12, 'v': 13, 'g': 14, 'y': 15, 'u': 16, 'p': 17, 'f': 18, '6': 19, 'w': 20, 'x': 21}


In [0]:
t1 = Tokenizer()


In [0]:
text1 = ['Decreased glucose-6-phosphate dehydrogenase activity along with oxidative stress affects visual contrast sensitivity in alcoholics.']


In [0]:
t1.fit_on_texts(text1)

In [0]:
sequences = t1.texts_to_sequences(text1)
print("sequences : ",sequences,'\n')


sequences :  [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]] 



In [0]:
print("word_index : ",t1.word_index)

word_index :  {'decreased': 1, 'glucose': 2, '6': 3, 'phosphate': 4, 'dehydrogenase': 5, 'activity': 6, 'along': 7, 'with': 8, 'oxidative': 9, 'stress': 10, 'affects': 11, 'visual': 12, 'contrast': 13, 'sensitivity': 14, 'in': 15, 'alcoholics': 16}
